---

- name: Unzip binary distribution archive
  ansible.builtin.unarchive:
    src: "{{ binaries_location }}/{{ item }}-{{ loki_binaries_platform_suffix }}.zip"
    remote_src: "{{ not loki_distribute_binaries_via_localhost }}"
    dest: /usr/local/bin
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
    mode: ug=rx,o=
  notify: restart loki

- name: Rename new binary
  ansible.builtin.command: mv /usr/local/bin/{{ item }}-{{ loki_binaries_platform_suffix }} /usr/local/bin/{{ item }}
  changed_when: true

- name: Remove binary archive
  ansible.builtin.file:
    path: /tmp/{{ item }}-{{ loki_binaries_platform_suffix }}.zip
    state: absent
  when: loki_distribute_binaries_via_localhost

...
