---

- name: Unzip binary distribution archive
  ansible.builtin.unarchive:
    src: "{{ binaries_location }}/{{ item }}-{{ loki_binaries_archive_suffix }}"
    remote_src: "{{ not loki_distribute_binaries_via_localhost }}"
    dest: /usr/local/bin
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
    mode: ug=rx,o=
  notify: restart loki

- name: Rename new binary
  ansible.builtin.command: mv /usr/local/bin/{{ item }}-linux-amd64 /usr/local/bin/{{ item }}

...
