---

- name: Download loki files to operator system
  ansible.builtin.get_url:
    url: "{{ binaries_location }}/{{ item }}-{{ loki_binaries_platform_suffix }}.zip"
    dest: /tmp
    mode: a=r
  become: false
  delegate_to: localhost
  run_once: true
  notify: cleanup loki archives

- name: Copy archive to target hosts
  ansible.builtin.copy:
    src: /tmp/{{ item }}-{{ loki_binaries_platform_suffix }}.zip
    dest: /tmp/

...
