---

- name: Download loki files to operator system
  ansible.builtin.get_url:
    url: "{{ binaries_location }}/{{ item }}-{{ loki_binaries_archive_suffix }}"
    dest: /tmp
    mode: a=r
  become: false
  delegate_to: localhost
  run_once: true

- name: Copy archive to target hosts
  ansible.builtin.copy:
    src: /tmp/{{ item }}-{{ loki_binaries_archive_suffix }}
    dest: /tmp/

- ansible.builtin.set_fact:
    binaries_location: /tmp

# TODO clean up temporary files later!

...
