---

- name: Set target version complementary to promtail's
  ansible.builtin.set_fact:
    loki_version: "{{ promtail_version }}"
  when: promtail_version is defined

- name: Set source URL base and binary
  ansible.builtin.set_fact:
    # possibly overridden in tasks/local_download.yml
    binaries_location: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}"
    loki_binaries: ["loki"]

- name: Extend binaries with logcli
  ansible.builtin.set_fact:
    loki_binaries: ["loki", "logcli"]
  when: loki_install_logcli

- name: Define a mapping from ansible_architecture to common names
  ansible.builtin.set_fact:
    _architectures:
      aarch64: arm64
      armv6l: arm
      armv7l: arm
      x86_64: amd64

- name: Define binary archive suffix
  ansible.builtin.set_fact:
    loki_binaries_platform_suffix: linux-{{ _architectures[ansible_architecture] }}

- name: Aggregate config file contents from variables
  ansible.builtin.set_fact:
    loki_config_file_contents:

      auth_enabled: "{{ loki_auth_enabled }}"

      server:
        http_listen_port: "{{ loki_server_http_listen_port }}"
        http_listen_address: "{{ loki_server_http_listen_address }}"
        log_level: "{{ loki_log_level }}"

      ingester: "{{ loki_ingester }}"

      schema_config:
        configs: "{{ loki_schema_configs }}"

      storage_config: "{{ loki_storage_config }}"

      table_manager:
        retention_deletes_enabled: true
        retention_period: "{{ loki_data_retention_period }}"

...
